# Generated by Django 3.0.3 on 2020-04-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200406_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='full.jpg', upload_to=''),
        ),
    ]
