# Generated by Django 3.0.3 on 2020-04-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200412_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply',
        ),
    ]
